-- Gameplay Mod Loader by Baris
-- Injects randomly a gameplay mod located in "content\\gameplay-loader" if the game started.

-- path, which should contain the different gameplay mods (extracted files, no CPKs!)
local contentPath  = ".\\BMPES\\gameplay-loader"
local gameplayModsCsv = "gameplay-mods.csv"
local version = "2.6"
local KEY_FAVORITE_GAMEPLAY_MOD = "favorite_gameplay_mod"
local KEY_IS_RANDOM_GAMEPLAY_MOD_ENABLED = "is_random_gameplay_mod_enabled"
local NO_MOD = "No Mod"

local gameplayMods = {}
local settings = {}
local manualIdx = 1
local selectedMod
local isGameplayModRandomEnabled
local infoText = "";

-- KEYS ----------------------------------------------------------------
local RELOAD_MAPS_KEY = 0x30 -- 0 key (not the NUMPAD zero!!)
local REMOVE_FAVORITE_SB_KEY = 0x36 -- 6 key (not the NUMPAD 6!!)
local SET_AS_FAVORITE_SB_KEY = 0x37 -- 7 key (not the NUMPAD 7!!)
local USE_FAVORITE_SB_KEY = 0x38 -- 8 key (not the NUMPAD 8!!)
local USE_RANDOM_GAMEPLAY_KEY = 0x39 -- 9 key (not the NUMPAD 9!!)
local DEL_TEXT_KEY = 0x2E
local PREVIOUS_SB_KEY = 0x21 -- Page Up
local NEXT_SB_KEY = 0x22 -- Page Down
------------------------------------------------------------------------

-- HELPER BEGIN --------------------------------------------------------
function t2s(t)
    local parts = {}
    for k, v in pairs(t) do
        parts[#parts + 1] = string.format("%s=%s", k, v)
    end
    table.sort(parts) -- sort alphabetically
    return string.format("{%s}", table.concat(parts, ", "))
end

function startsWith(str, start)
    return str:sub(1, #start) == start
end

function string:split(sep)
    local sep, fields = sep or ":", {}
    local pattern = string.format("([^%s]+)", sep)
    self:gsub(pattern, function(c) fields[#fields + 1] = c end)

    return fields
end

function getRandomIdx()
    -- get randomly a gameplay mod
    math.randomseed(os.clock() * 100000000000)

    return math.random(1, #gameplayMods)
end

function isGameplayFile(filename)
    if      string.match(filename, "common\\match\\constant\\constant_match.bin")           or
            string.match(filename, "common\\match\\constant\\constant_player.bin")          or
            string.match(filename, "common\\match\\constant\\constant_positionCK.bin")      or
            string.match(filename, "common\\match\\constant\\constant_positionPK.bin")      or
            string.match(filename, "common\\match\\constant\\constant_shootAging.bin")      or
            string.match(filename, "common\\match\\constant\\constant_stadium.bin")         or
            string.match(filename, "common\\match\\constant\\constant_team.bin")            or
            string.match(filename, "common\\match\\constant\\constant_tutorial.bin")        or
            string.match(filename, "common\\match\\constant\\constant_tutorialConsole.bin") or
            string.match(filename, "common\\anime\\")
    then
        return true
    else
        return false
    end
end

function readMapTeams(path, sep)
    sep = sep or ','
    local csvFile = {}
    local file = assert(io.open(path, "r"))

    -- add option "no mods" which disabled loading a gameplay mod
    table.insert(csvFile, NO_MOD)

    for line in file:lines() do
        if not startsWith(line, "#") then
            local fields = line:split(sep)
            if #fields == 1 then
                local gameplayModFolderName = fields[1]
                table.insert(csvFile, gameplayModFolderName)
            end
        end
    end
    file:close()

    return csvFile
end

function tableContainsValue(table, desiredValue)
    for _, value in pairs(table) do
        if value == desiredValue then
            return true
        end
    end

    return false
end

--- copied from ScoreboardServer.lua, slightly adjusted regex to read values with spaces
local function load_ini(filename)
    local t = {}
    local data = assert(io.lines(contentPath .. "\\" .. filename))

    for line in data do
        local name, value = string.match(line, "^([%w_]+)%s*=%s*([-%w%d. ]+)")
        if name and value then
            value = tonumber(value) or value
            t[name] = value
        end
    end
    return t
end

--- copied from ScoreboardServer.lua
local function save_ini(filename)
    local f = io.open(contentPath .. "\\" .. filename, "wt")
    f:write(string.format("# GameplayLoader settings. Generated by GameplayLoader.lua\n"))
    f:write("\n")
    local keys = {}
    for name,value in pairs(settings) do
        keys[#keys + 1] = name
    end

    table.sort(keys)

    for i,name in ipairs(keys) do
        local value = settings[name]
        f:write(string.format("%s = %s\n", name, value))
    end
    f:write("\n")
    f:close()
end

local function getFavoriteGameplayMod()
    local favoriteGameplayMod = settings[KEY_FAVORITE_GAMEPLAY_MOD]

    if favoriteGameplayMod and tableContainsValue(gameplayMods, favoriteGameplayMod) then
        return favoriteGameplayMod
    else
        return nil
    end
end

local function getGameplayModIdx(gameplayMod)
    for idx, value in pairs(gameplayMods) do
        if value == gameplayMod then
            return idx
        end
    end

    return nil
end
-- HELPER END ----------------------------------------------------------



-- EVENTS BEGIN --------------------------------------------------------
function livecpk_make_key(ctx, filename)
    -- don't load any gameplay mod if NO_MOD is chosen
    if selectedMod ~= nil and selectedMod ~= NO_MOD and isGameplayFile(filename) then
        --log(selectedMod .. "\\" .. filename)

        return selectedMod .. "\\" .. filename
    end
end

function livecpk_get_filepath(ctx, filename, key)
    if key then
        return string.format("%s\\%s", contentPath, key)
    end
end

function set_teams(ctx, home_team_id, away_team_id)

    -- select only random gameplay mod if it was enabled
    isGameplayModRandomEnabled = settings[KEY_IS_RANDOM_GAMEPLAY_MOD_ENABLED]
	
    if isGameplayModRandomEnabled == "true" then
        manualIdx = getRandomIdx()
        selectedMod = gameplayMods[manualIdx]
        -- infoText = infoText .. string.format("Random gameplay mod chosen: %s\n", selectedMod)
    end
end

local function overlay_on(ctx)
    return string.format([[
Version %s
               [0]  to reload map %s files
[PageUp][PageDown]  to manually select previous/next gameplay mod
             [DEL]  to clear info messages
               [6]  to remove current favorite gameplay mod
               [7]  to set current selection as favorite gameplay mod
               [8]  to use your favorite gameplay mod
               [9]  to enable/disable automatically choosing a random gameplay mod per match

      Selected Gameplay Mod: %s
Enabled Random Gameplay Mod: %s

%s
]],
        version, gameplayModsCsv, selectedMod, isGameplayModRandomEnabled, infoText)
end

local function key_down(ctx, vkey)
    if vkey == DEL_TEXT_KEY then
        infoText = ""
    end

    if vkey == RELOAD_MAPS_KEY then
        gameplayMods = readMapTeams(contentPath .. "\\" .. gameplayModsCsv, ";");

        settings = load_ini("config.ini")
    end

    if vkey == PREVIOUS_SB_KEY then
        manualIdx = ((manualIdx - 1) + #gameplayMods - 1) % #gameplayMods + 1
        selectedMod = gameplayMods[manualIdx]
    end

    if vkey == NEXT_SB_KEY then
        manualIdx = manualIdx % #gameplayMods + 1
        selectedMod = gameplayMods[manualIdx]
    end

    if vkey == SET_AS_FAVORITE_SB_KEY then
        if selectedMod and tableContainsValue(gameplayMods, selectedMod) then
            settings[KEY_FAVORITE_GAMEPLAY_MOD] = selectedMod
            save_ini("config.ini")
            infoText = infoText .. string.format("Gameplay mod %s saved as favorite\n", selectedMod)
        else
            infoText = infoText .. "Could not save favorite gameplay mod\n"
        end
    end

    if vkey == REMOVE_FAVORITE_SB_KEY then
        local favoriteGameplayMod = settings[KEY_FAVORITE_GAMEPLAY_MOD]
        settings[KEY_FAVORITE_GAMEPLAY_MOD] = ""
        save_ini("config.ini")
        infoText = infoText .. string.format("Removed gameplay mod %s as favorite\n", favoriteGameplayMod)
    end

    if vkey == USE_FAVORITE_SB_KEY then
        local favoriteGameplayMod = getFavoriteGameplayMod()

        if favoriteGameplayMod then
            infoText = infoText .. string.format("Favorite gameplay mod %s set as active\n", favoriteGameplayMod)
            manualIdx = getGameplayModIdx(favoriteGameplayMod)
            selectedMod = favoriteGameplayMod
        else
            infoText = infoText .. string.format("Could not find favorite gameplay mod\n")
        end
    end

    if vkey == USE_RANDOM_GAMEPLAY_KEY then
		local settingsIsRandomEnabled = settings[KEY_IS_RANDOM_GAMEPLAY_MOD_ENABLED]
		if (settingsIsRandomEnabled == "false") then
			isGameplayModRandomEnabled = "true"
		elseif (settingsIsRandomEnabled == "true") then
			isGameplayModRandomEnabled = "false"
		end
		
        settings[KEY_IS_RANDOM_GAMEPLAY_MOD_ENABLED] = isGameplayModRandomEnabled
        save_ini("config.ini")
        infoText = infoText .. string.format("Random Gameplay mod enabled: %s\n", isGameplayModRandomEnabled)
    end

end
-- EVENTS END --------------------------------------------------------



function init(ctx)
    if contentPath:sub(1, 1) == "." then
        contentPath = ctx.sider_dir .. contentPath
    end

    gameplayMods = readMapTeams(contentPath .. "\\" .. gameplayModsCsv, ";");
    settings = load_ini("config.ini")

    local favoriteGameplayMod = getFavoriteGameplayMod()
    if favoriteGameplayMod ~= nil then
        manualIdx = getGameplayModIdx(favoriteGameplayMod)
    end

    selectedMod = gameplayMods[manualIdx]
    isGameplayModRandomEnabled = settings[KEY_IS_RANDOM_GAMEPLAY_MOD_ENABLED]
    if isGameplayModRandomEnabled == nil then
        isGameplayModRandomEnabled = false
    end

    ctx.register("livecpk_make_key", livecpk_make_key)
    ctx.register("livecpk_get_filepath", livecpk_get_filepath)
    ctx.register("overlay_on", overlay_on)
    ctx.register("key_down", key_down)
    ctx.register("set_teams", set_teams)
end

return { init = init }