[sider]
debug = 0
close.on.exit = 0
start.minimized = 1

free.side.select = 1
livecpk.enabled = 1

start.game = 
exe.name = "\PES2021.exe"

; enforce number of match minutes here
; you can set any value from 1 to 255, although you probably
; do not want to go higher than 90, because it will be weird :-)
; 0 - disables this feature.
match.minutes = 0

; to see mstats.lua working, set this to 1
match-stats.enabled = 1

; LIVE CPK
cpk.root = ".\livecpk\MODGAMESX_BootsAndGloves"
cpk.root = ".\livecpk\MODGAMESX_AnimePlayer
cpk.root = ".\livecpk\MODGAMESX_Chuteiras
cpk.root = ".\livecpk\MODGAMESX_Database"
cpk.root = ".\livecpk\MODGAMESX_Adboards"
cpk.root = ".\livecpk\MODGAMESX_Badges"
cpk.root = ".\livecpk\MODGAMESX_CoachML"
cpk.root = ".\livecpk\MODGAMESX_CompetitionMenus"
cpk.root = ".\livecpk\MODGAMESX_Chants"
cpk.root = ".\livecpk\MODGAMESX_Faces"
cpk.root = ".\livecpk\MODGAMESX_Faces_2"
cpk.root = ".\livecpk\MODGAMESX_Faces_3"
cpk.root = ".\livecpk\MODGAMESX_Faces_4"
cpk.root = ".\livecpk\MODGAMESX_Faces_5"
cpk.root = ".\livecpk\MODGAMESX_Faces_6"
cpk.root = ".\livecpk\MODGAMESX_Faces_7"
cpk.root = ".\livecpk\MODGAMESX_Faces_8"
cpk.root = ".\livecpk\MODGAMESX_Faces_9"
cpk.root = ".\livecpk\MODGAMESX_Faces_10"
cpk.root = ".\livecpk\MODGAMESX_Faces_Legends"
cpk.root = ".\livecpk\MODGAMESX_Font"
cpk.root = ".\livecpk\MODGAMESX_Gamepad"
;cpk.root = ".\livecpk\MODGAMESX_Gamepad_4K"
cpk.root = ".\livecpk\MODGAMESX_GoalSongs"
cpk.root = ".\livecpk\MODGAMESX_Graphics"
cpk.root = ".\livecpk\MODGAMESX_Intros"
cpk.root = ".\livecpk\MODGAMESX_Kits"
cpk.root = ".\livecpk\MODGAMESX_Logos"
cpk.root = ".\livecpk\MODGAMESX_Menu"
cpk.root = ".\livecpk\MODGAMESX_Minifaces_00"
cpk.root = ".\livecpk\MODGAMESX_Minifaces_0"
cpk.root = ".\livecpk\MODGAMESX_Minifaces_1"
cpk.root = ".\livecpk\MODGAMESX_Minifaces_2"
cpk.root = ".\livecpk\MODGAMESX_Minifaces_3"
cpk.root = ".\livecpk\MODGAMESX_Minifaces_4"
cpk.root = ".\livecpk\MODGAMESX_Minifaces_5"
cpk.root = ".\livecpk\MODGAMESX_Minifaces_6"
cpk.root = ".\livecpk\MODGAMESX_Minifaces_7"
cpk.root = ".\livecpk\MODGAMESX_Minifaces_8"
cpk.root = ".\livecpk\MODGAMESX_Minifaces_9"
cpk.root = ".\livecpk\MODGAMESX_Minifaces_10"
cpk.root = ".\livecpk\MODGAMESX_Minifaces_11"
cpk.root = ".\livecpk\MODGAMESX_Minifaces_12"
cpk.root = ".\livecpk\MODGAMESX_Minifaces_13"
cpk.root = ".\livecpk\MODGAMESX_Minifaces_14"
cpk.root = ".\livecpk\MODGAMESX_NationalAnthems"
cpk.root = ".\livecpk\MODGAMESX_MenuAnthems"
cpk.root = ".\livecpk\MODGAMESX_RefereeColors"
cpk.root = ".\livecpk\MODGAMESX_Turfs"
cpk.root = ".\livecpk\MODGAMESX_Stadiums"
cpk.root = ".\livecpk\MODGAMESX_Music"
cpk.root = ".\livecpk\Immersion Mod 2.0"
cpk.root = ".\livecpk\MODGAMESX_CUP_LIB_LEGENDS"
cpk.root = ".\livecpk\MODGAMESX_KONAMI_CUP_CHAMPIONS (ON)"
cpk.root = ".\livecpk\MODGAMESX_KONAMI_CUP_LIBERTADORES (ON)"
cpk.root = ".\livecpk\MODGAMESX_KONAMI_CUP_WORLD_CUP (ON)"
cpk.root = ".\livecpk\MODGAMESX_KONAMI_CUP_UEFA_LEGENDS (ON)"
cpk.root = ".\livecpk\MODGAMESX_KONAMI_CUP_WORLD_CLUB (ON)"

; Lua settings
lua.enabled = 1
luajit.ext.enabled = 1

; LUA MODULES
lua.module = "lib\CommonLib.lua"

lua.module = "IntroServer.lua"
lua.module = "tournament_anth_tunnel.lua"
lua.module = "Entrance_fix.lua"
lua.module = "Entrance.lua"
lua.module = "ChoreoServer.lua"
lua.module = "Stadium_CornerFlag.lua"
lua.module = "StadiumServer.lua"
lua.module = "Stadium_Banner.lua"
lua.module = "Stadium_Board.lua"

lua.module = "kserv.lua"
lua.module = "kitglobal.lua"
lua.module = "SleeveBadge.lua"
lua.module = "BallServer.lua"
lua.module = "ScoreboardServer.lua"
lua.module = "commentary-server.lua"
lua.module = "RefKitServer.lua"
lua.module = "MenuServer.lua"
lua.module = "GoalsongServer.lua"
lua.module = "BallBoysServer.lua"
;lua.module = "CutScenes.lua"

lua.module = "env.lua"
lua.module = "etrace.lua"
lua.module = "jittest.lua"
lua.module = "zlibtest.lua"
lua.module = "matchset.lua"
lua.module = "netblock.lua"

;lua.module = "camera.lua"
;lua.module = "timeaccel.lua"
;lua.module = "tracer.lua"
;lua.module = "inputdemo.lua"
;lua.module = "snow.lua"
;lua.module = "facedump.lua"
;lua.module = "filedump2.lua"
;lua.module = "kitrewrite.lua"
;lua.module = "pointers.lua"
;lua.module = "mstats.lua"
;lua.module = "gc64test.lua"


; Overlay settings
; location on screen: top|bottom
; size of the font (0 - automatic)
; overlay hot keys: 
; 0x20 - [space] - toggle overlay on/off
; 0x31 - [1] - pass overlay control to next module
; 0xc0 - [~] - pass overlay control to previous module
; colors are in RRGGBBAA format
overlay.enabled = 1
overlay.on-from-start = 0
overlay.location = "top"
overlay.font-size = 0
overlay.font = "Consolas"
overlay.vkey.toggle = 0x20
overlay.vkey.next-module = 0x31
overlay.vkey.prev-module = 0xc0
overlay.background-color = "102010c0"
overlay.text-color = "80ff80c0"
overlay.image-alpha-max = 0.8
overlay.toggle.sound = "toggle.wav"
overlay.toggle.sound-volume = 0.5

; Reload modified modules
; Default combination: Shift-R
vkey.reload-1 = 0x10
vkey.reload-2 = 0x52

